### PR TITLE
fix: Update Rust toolchain version to 1.95.0 in configuration

### LINKED ISSUE #146: Build broken on main: cfg_select! requires Rust 1.95, toolchain pins 1.92.0
# build: rusqlite 0.40.0 bump pulls in `cfg_select!` (Rust 1.95) but the toolchain is pinned to Rust 1.92.0

## Summary

`cargo build` / `nix build` fails on the latest `main` (`17a8d37`).

The transitive dependency `libsqlite3-sys 0.38.0` uses the `cfg_select!` macro in its `build.rs`, but that macro was **stabilized in Rust 1.95**. This repository pins **`channel = "1.92.0"`** in `rust-toolchain.toml`, so `cfg_select!` is treated as an unstable feature and the build fails to compile.

## Offending commit

- Last working commit: `22598d35` (2026-05-24) — rusqlite 0.39.0 line
- Breaking commit: **`3b0f8f35` (2026-05-31) `chore(deps): bump rusqlite from 0.39.0 to 0.40.0 (#139)`**
  - rusqlite 0.40.0 pulls in `libsqlite3-sys 0.38.0`
  - `libsqlite3-sys 0.38.0`'s `build.rs` uses `cfg_select!`
  - `cfg_select!` was stabilized in Rust 1.95 ([PR #149783](https://github.com/rust-lang/rust/pull/149783))

## Error log

```text
error[E0658]: use of unstable library feature `cfg_select`
   --> .../libsqlite3-sys-0.38.0/build.rs:110:9
    |
110 |         cfg_select! {
    |         ^^^^^^^^^^
    |
    = note: see issue #115585 <https://github.com/rust-lang/rust/issues/115585> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `libsqlite3-sys` (build script) due to 1 previous error
```

## Steps to reproduce

```sh
cargo build
```

## Environment

- platform: aarch64-darwin (macOS)
- pinned Rust: `rust-toolchain.toml` → `channel = "1.92.0"`

## Suggested fixes (either one)

1. Bump `channel` in `rust-toolchain.toml` to `1.95.0` or later (to keep up with the newer dependency that uses `cfg_select!`)
2. Revert `rusqlite` back to `0.39.0` (revert #139 to avoid `libsqlite3-sys 0.38.0`)

### PR DESCRIPTION
**Pull request by mozumasu**
## Summary

Fixes #146

Bump `rust-toolchain.toml` from `1.92.0` to `1.95.0` to fix the build failure on `main`.

The `rusqlite` 0.40.0 bump (#139) pulled in `libsqlite3-sys 0.38.0`, whose `build.rs` uses the `cfg_select!` macro. This macro was stabilized in Rust 1.95, so the pinned 1.92.0 toolchain fails with `E0658`.

## Changes

- `rust-toolchain.toml`: `channel = "1.92.0"` → `channel = "1.95.0"`
- Fixed 4 `clippy::unnecessary_sort_by` warnings (`sort_by` → `sort_by_key`) that surfaced with the new clippy in 1.95.0
  - `src/version/registries/crates_io.rs`
  - `src/version/registries/github.rs`
  - `src/version/registries/jsr.rs`
  - `src/version/registries/npm.rs`

## Verification

- `cargo build` — passes
- `cargo clippy --all-targets --all-features` — no warnings
- `cargo fmt --all -- --check` — passes
- `cargo test` — all tests pass
- Tested locally on aarch64-darwin
- `./target/release/version-lsp --version` — outputs `version-lsp 0.5.1`

### CODE REVIEW

**Comment by skanehira** [comment]
@mozumasu 
PRありがとうございます
nix buildが落ちているので、見てもらえますか 🙏

**Comment by mozumasu** [comment]
@skanehira 
`nix flake update rust-overlay` で更新して対応しました🙇
[895a650](https://github.com/skanehira/version-lsp/pull/147/commits/895a650885db221c1a981d19c080752de4220d7b)

**Comment by skanehira** [comment]
@mozumasu Thanks :)
